name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  LC_ALL: en_US.UTF-8

jobs:
  Build:
    timeout-minutes: 5
    name: Build calculator
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build
        shell: bash
        run: mvn -V -U -e -ntp clean install
